var layer1 = document.createElement("li")
layer1.setAttribute('class', 'rtsLI')
var layer2 = document.createElement("a")
layer2.setAttribute('class', 'rtsLink')
var layer3 = document.createElement("span")
layer3.setAttribute('class', 'rtsOut')
var layer4 = document.createElement("span")
layer4.setAttribute('class', 'rtsIn')
var layer5 = document.createElement("span")
layer5.setAttribute('class', 'rtsrtsTxtOut')
var text = document.createTextNode("**TEST**")
layer1.appendChild(layer2)
layer2.appendChild(layer3)
layer3.appendChild(layer4)
layer4.appendChild(layer5)
layer5.appendChild(text)
document.querySelector("#ctl00_ctl00_phMain_phMain_rtsPatient > div > ul").appendChild(layer1)